name: Releases

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.tag }}
    - name: Generate Prerelease Release Notes
      run: |
        mkdir release
        cp README.md ./release
        tar czf release.tar.gz ./release
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.tag }}
        files: |
          release.tar.gz
