name: Releases

on: 
push:
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
    - name: Generate Prerelease Release Notes
      run: |
        mkdir release
        cp README.md ./release
        tar czf release.tar.gz ./release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: release.tar.gz
        pth: release.tar.gz
